/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jokenpo;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Adriano
 */
public class MainForm extends javax.swing.JFrame {

    private String playerName;
    private int playerScore;
    private int cpuScore;
    private int rodada;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        this.setTitle("Jokenpo");
        playerName = null;
        playerScore = 0;
        cpuScore = 0;
        rodada = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kenGroup = new javax.swing.ButtonGroup();
        panelResultado = new javax.swing.JPanel();
        lblPlayer = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblCPUName = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        panelJogada = new javax.swing.JPanel();
        rbPapel = new javax.swing.JRadioButton();
        rbPedra = new javax.swing.JRadioButton();
        rbTesoura = new javax.swing.JRadioButton();
        btnPlay = new javax.swing.JButton();
        panelScore = new javax.swing.JPanel();
        lblPlayerScoreName = new javax.swing.JLabel();
        lblPlayerScoreRes = new javax.swing.JLabel();
        lblCPUScoreName = new javax.swing.JLabel();
        lblCPUScoreRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Rodada #0"));

        lblPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jokenpo/Images/ken_empty.png"))); // NOI18N
        lblPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jokenpo/Images/ken_empty.png"))); // NOI18N

        lblPlayerName.setText("Jogador 1");

        lblCPUName.setText("Jogador 2");

        lblResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jokenpo/Images/res_empty.png"))); // NOI18N

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayer)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblCPU)
                .addContainerGap())
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCPUName)
                .addGap(98, 98, 98))
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPU)
                    .addComponent(lblPlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayerName)
                    .addComponent(lblCPUName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addContainerGap())
        );

        panelJogada.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogada"));
        panelJogada.setToolTipText("");

        kenGroup.add(rbPapel);
        rbPapel.setSelected(true);
        rbPapel.setText("Papel");

        kenGroup.add(rbPedra);
        rbPedra.setText("Pedra");

        kenGroup.add(rbTesoura);
        rbTesoura.setText("Tesoura");

        btnPlay.setText("Jogar");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJogadaLayout = new javax.swing.GroupLayout(panelJogada);
        panelJogada.setLayout(panelJogadaLayout);
        panelJogadaLayout.setHorizontalGroup(
            panelJogadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJogadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJogadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbPedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbTesoura, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelJogadaLayout.setVerticalGroup(
            panelJogadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJogadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbPapel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTesoura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelScore.setBorder(javax.swing.BorderFactory.createTitledBorder("Placar"));

        lblPlayerScoreName.setText("Jogador 1");

        lblPlayerScoreRes.setText("# 0");

        lblCPUScoreName.setText("CPU");

        lblCPUScoreRes.setText("# 0");

        javax.swing.GroupLayout panelScoreLayout = new javax.swing.GroupLayout(panelScore);
        panelScore.setLayout(panelScoreLayout);
        panelScoreLayout.setHorizontalGroup(
            panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPUScoreName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlayerScoreName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlayerScoreRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCPUScoreRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelScoreLayout.setVerticalGroup(
            panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoreLayout.createSequentialGroup()
                .addComponent(lblPlayerScoreName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlayerScoreRes)
                .addGap(18, 18, 18)
                .addComponent(lblCPUScoreName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCPUScoreRes)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJogada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.lblCPUName.setText(" ");
        this.lblPlayerName.setText(" ");

        while (playerName == null) {
            this.playerName = JOptionPane.showInputDialog(this, "Qual é seu nome?", "Jogador 1");
        }

        this.setTitle("Jokenpo - " + playerName);
        this.lblPlayerScoreName.setText(playerName);
    }//GEN-LAST:event_formWindowOpened

    public static int randInt(int min, int max) {
        java.util.Random rand = new java.util.Random();
        return rand.nextInt((max - min) + 1) + min;
    }

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        ImageIcon kenPlayer = new ImageIcon(getClass().getResource("/jokenpo/Images/ken_empty.png"));
        ImageIcon kenCPU = new ImageIcon(getClass().getResource("/jokenpo/Images/ken_empty.png"));
        ImageIcon kenRes;
        // ken 0 = papel, 1 = pedra, 2 = tesoura
        int playerken, cpuken;
        playerken = 0;

        if (this.kenGroup.getSelection().equals(this.rbPapel.getModel())) {
            kenPlayer = new ImageIcon(getClass().getResource("/jokenpo/Images/papel.png"));
            playerken = 0;
        } else if (this.kenGroup.getSelection().equals(this.rbPedra.getModel())) {
            kenPlayer = new ImageIcon(getClass().getResource("/jokenpo/Images/pedra.png"));
            playerken = 1;
        } else if (this.kenGroup.getSelection().equals(this.rbTesoura.getModel())) {
            kenPlayer = new ImageIcon(getClass().getResource("/jokenpo/Images/tesoura.png"));
            playerken = 2;
        }

        cpuken = randInt(0, 2);

        switch (cpuken) {
            case 0:
                kenCPU = new ImageIcon(getClass().getResource("/jokenpo/Images/papel.png"));
                break;
            case 1:
                kenCPU = new ImageIcon(getClass().getResource("/jokenpo/Images/pedra.png"));
                break;
            case 2:
                kenCPU = new ImageIcon(getClass().getResource("/jokenpo/Images/tesoura.png"));
                break;
        }
        
        if ((playerken == 0 && cpuken == 1) ||
                (playerken == 1 && cpuken == 2) ||
                (playerken == 2 && cpuken == 0)) {
            kenRes = new ImageIcon(getClass().getResource("/jokenpo/Images/win.png"));
            playerScore++;
        } else if ((playerken == 0 && cpuken == 0) ||
                (playerken == 1 && cpuken == 1) ||
                (playerken == 2 && cpuken == 2)) {
            kenRes = new ImageIcon(getClass().getResource("/jokenpo/Images/draw.png"));
        } else {
            kenRes = new ImageIcon(getClass().getResource("/jokenpo/Images/lose.png"));
            cpuScore++;
        }
        
        rodada++;
        TitledBorder border = (TitledBorder)this.panelResultado.getBorder();
        border.setTitle("Rodada #" + rodada);
        this.panelResultado.setBorder(border);
        this.panelResultado.repaint();
        
        this.lblPlayerName.setText(playerName);
        this.lblCPUName.setText("CPU");
        this.lblPlayerScoreRes.setText("# " + playerScore);
        this.lblCPUScoreRes.setText("# " + cpuScore);
        this.lblPlayer.setIcon(kenPlayer);
        this.lblCPU.setIcon(kenCPU);
        this.lblResultado.setIcon(kenRes);
    }//GEN-LAST:event_btnPlayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.ButtonGroup kenGroup;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCPUName;
    private javax.swing.JLabel lblCPUScoreName;
    private javax.swing.JLabel lblCPUScoreRes;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPlayerScoreName;
    private javax.swing.JLabel lblPlayerScoreRes;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panelJogada;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelScore;
    private javax.swing.JRadioButton rbPapel;
    private javax.swing.JRadioButton rbPedra;
    private javax.swing.JRadioButton rbTesoura;
    // End of variables declaration//GEN-END:variables
}
